// Generates supabase/seeds/quotes_seed.sql with 365 each for ko/en/ko_self.
// Diversity rule: dedupe within each lang, length 5..80.
const fs = require('fs');
const path = require('path');

function esc(s) { return s.replace(/'/g, "''"); }
function uniqPush(arr, set, t) {
  const k = t.trim();
  if (k.length < 5 || k.length > 80) return false;
  if (set.has(k)) return false;
  set.add(k); arr.push(k); return true;
}

// ---------------- KO running (365) ----------------
const koHand = [
  '뛴 만큼 가벼워진다.',
  '한 발만 더, 그게 어제와 다른 나야.',
  '느려도 멈추지 않으면 도착한다.',
  '숨이 차야 살아있는 게 느껴진다.',
  '신발끈만 묶어도 절반은 성공이다.',
  '비 오는 날의 1km는 맑은 날의 5km만큼 값지다.',
  '러닝은 도망이 아니라 정리정돈이다.',
  '오늘의 5분이 내일의 10분을 만든다.',
  '땀은 거짓말을 안 한다.',
  '심박수가 오를수록 잡생각은 떨어진다.',
  '발이 무겁다는 건 마음이 무겁다는 뜻이다.',
  '러닝화가 닳는 만큼 멘탈이 단단해진다.',
  '천천히 가도 괜찮아, 너만의 페이스가 정답이다.',
  '오르막은 다리가 아니라 마음으로 오르는 거야.',
  '내리막에서는 욕심내지 말고 즐겨라.',
  '시작 전 1분 망설임이 가장 큰 적이다.',
  '컨디션 좋은 날만 뛰면 영원히 못 뛴다.',
  '러닝은 결과가 아니라 출석이다.',
  '오늘의 나는 어제의 나를 이기면 충분해.',
  '거리보다 빈도, 빈도보다 지속.',
  '뛰고 나서 후회한 적은 단 한 번도 없다.',
  '비교 대상은 옆 러너가 아니라 어제의 나.',
  '러닝화는 핑계를 모른다.',
  '걷기 시작은 뛰기 절반의 용기다.',
  '심장은 뛸수록 강해진다, 마음도 똑같다.',
  '땀 흘린 날의 잠은 두 배로 달다.',
  '뛰는 동안만큼은 모든 알림이 무음이다.',
  '한 바퀴만 더, 라는 마법의 주문.',
  '코스가 별로면 마음이 별로인 거야.',
  '신호등 앞에서도 제자리뛰기는 멈추지 마.',
  '뜀박질은 가장 저렴한 자기관리다.',
  '러닝은 공짜인데 효과는 명품이다.',
  '쉬는 날도 트레이닝의 일부야.',
  '회복 없는 성장은 환상이다.',
  '근육통은 어제의 영수증이다.',
  '천천히가 결국 가장 빠르다.',
  '빨리 가려면 혼자, 멀리 가려면 같이.',
  '아침 러닝은 하루를 두 번 사는 기분.',
  '저녁 러닝은 하루를 리셋하는 마법.',
  '러닝 후 샤워는 인생의 작은 사치.',
  '뛰는 사람만 아는 새벽의 색깔이 있다.',
  '바람을 가르는 게 아니라 바람과 친해지는 일.',
  '비 오는 날 뛰면 영화 주인공이 된 기분.',
  '러닝은 명상의 가장 시끄러운 형태.',
  '내 발걸음이 내 일기장이다.',
  '지친 날일수록 짧게라도 나가자.',
  '컨디션은 따라오는 거지 기다리는 게 아니다.',
  '한 걸음의 무게는 0g, 누적은 평생.',
  '오늘 안 뛰면 내일은 두 배로 무겁다.',
  '러닝은 내가 아직 살아있다는 증거다.',
  '빨라지려고 뛰지 말고 멀어지려고 뛰자.',
  '도시의 소음을 발걸음으로 덮어보자.',
  '심호흡은 공짜인데 효과는 약보다 좋다.',
  '러닝은 어른의 뜀박질이다.',
  '신호등 빨간불은 회복 시간이다.',
  '한강이 동기부여라면 그것도 좋다.',
  '운동장 한 바퀴는 400m, 마음은 한참.',
  '발바닥이 뜨거워질 때 기분은 시원해진다.',
  '한 번 멈추면 두 번 멈추기 쉽다.',
  '뛸수록 식욕이 정직해진다.',
  '잠이 깊어지는 가장 쉬운 방법.',
  '러닝화 한 켤레의 수명은 800km라고 한다.',
  '중간에 걸어도 러닝은 러닝이다.',
  '땀이 식기 전에 다음 약속을 잡아라.',
  '러닝일지는 미래의 나에게 보내는 편지.',
  '뛰는 게 무서울 땐 동네 한 바퀴부터.',
  '오늘의 러닝은 내일의 면역력이다.',
  '날씨가 선택지가 되면 못 뛴다.',
  '바람 부는 날엔 페이스 신경 끄자.',
  '폼이 무너져도 안 뛰는 것보단 백배 낫다.',
  '러닝은 친구를 닮은 취미다.',
  '뛰면 적어도 한 가지 고민은 사라진다.',
  '운동복은 옷장이 아니라 현관에 두자.',
  '준비물은 단 두 개, 신발과 의지.',
  '러닝은 가장 정직한 데이터다.',
  '심박존은 내 몸의 신호등이다.',
  '쉬어도 죄책감 갖지 마, 회복도 훈련이다.',
  '내 페이스는 내가 정한다.',
  '러닝은 자기 자신과의 데이트다.',
  '거울보다 GPS가 정직하다.',
  '뛴 거리는 사라지지 않는다, 몸에 남는다.',
  '느린 러너도 러너다.',
  '오늘 1km, 내일 1km, 그게 마라톤이다.',
  '결승선은 매일의 현관문이다.',
  '뛰지 않으면 알 수 없는 풍경이 있다.',
  '신발끈은 결심의 시작점.',
  '뛰는 순간만큼은 자유다.',
  '폼롤러는 러닝화의 영원한 짝꿍.',
  '스트레칭 5분이 다음 주를 살린다.',
  '발목은 가장 작은 영웅이다.',
  '엉덩이 근육이 깨면 러닝이 가벼워진다.',
  '코어가 살아야 자세가 산다.',
  '호흡은 박자, 박자는 음악.',
  '뛸 땐 어깨에 힘 빼는 게 첫 단계.',
  '시선은 멀리, 발은 가볍게.',
  '러닝은 끈기 트레이닝이지 속도 트레이닝이 아니다.',
  '거리보다 자세, 자세보다 호흡.',
  '오늘 멈추면 내일은 다시 시작이 아니라 처음부터.',
  '러닝은 출근 전 가장 큰 성취감.',
  '하늘이 흐려도 발걸음은 맑게.',
  '땀 흘리는 게 어른의 의무는 아니지만 권리다.',
  '뛴 날과 안 뛴 날의 잠 질은 다르다.',
  '심박수보다 빈도가 중요하다.',
  '훈련일지는 자존감의 통장이다.',
  '느슨한 페이스도 페이스다.',
  '오늘의 1km는 미래의 보험이다.',
  '근력운동과 러닝은 형제다.',
  '한 발 한 발이 모여 한 달이 된다.',
  '뛰면서 듣는 노래는 두 배로 좋다.',
  '러닝은 핸드폰 알림과 가장 먼 시간.',
  '운동화 끈이 풀리는 건 멈추라는 신호일 뿐.',
  '뛸 땐 페이스보다 자세에 집중하자.',
  '내일의 컨디션은 오늘 잠이 결정한다.',
  '몸이 무거우면 거리를 줄여라, 멈추진 마라.',
  '러닝은 기록 경쟁이 아니라 출석 체크다.',
  '뛸수록 도시가 작아 보인다.',
  '신호등이 많은 코스는 인터벌 코스다.',
  '비 오는 날도 코스의 일부다.',
  '눈 오는 날의 러닝은 평생 기억된다.',
  '운동복 빨래는 자신감의 보존이다.',
  '러닝은 계절을 가장 가까이 느끼는 방법.',
  '봄바람은 페이스를 올려준다.',
  '여름밤의 러닝은 청춘의 맛.',
  '가을 공기는 러너의 보너스다.',
  '겨울 러닝은 정신력의 시험장.',
  '덥다고 빠지지 말고 짧게 가자.',
  '춥다고 빠지지 말고 워밍업 길게.',
  '러닝은 휴가 중에도 가능한 유일한 헬스장.',
  '뛰는 사람은 어디서나 러너다.',
  '오늘 뛴 5km, 내일 자랑할 거리.',
  '안 뛰면 그날만 손해, 뛰면 내일까지 이득.',
  '러닝화 매일 신어보면 안다, 오늘의 컨디션을.',
  '신발 갈 때가 됐다는 건 잘 뛰었다는 증거.',
  '러닝은 계산기가 아니다.',
  '심박수에 너무 매달리지 말자.',
  '시계 없이 뛰어보는 날도 필요하다.',
  '러닝은 가성비 최고의 자기관리다.',
  '뛰는 즐거움은 설명 말고 경험.',
  '땀 한 방울이 작은 자존감 한 알.',
  '러닝은 마음의 수도꼭지를 여는 일.',
  '몸이 가벼워지면 결정도 빨라진다.',
  '뛴 날의 나는 조금 더 친절하다.',
  '러닝은 가장 빠른 기분 전환.',
  '심호흡 세 번이면 다시 뛸 수 있다.',
  '한 정거장 먼저 내려서 뛰어보자.',
  '엘리베이터 대신 계단, 그것도 훈련.',
  '러닝은 일단 나가는 게 90%다.',
  '신발 신는 순간이 가장 어렵다.',
  '뛰기 시작하면 후회는 사라진다.',
  '오늘만 살자는 마음으로 1km만.',
  '러닝은 거짓말 못 하는 친구다.',
  '뛴 날과 안 뛴 날의 거울은 다르다.',
  '운동복이 익숙해지면 인생도 바뀐다.',
  '뛸 때만큼은 SNS에서 도망치자.',
  '러닝은 디톡스의 다른 이름.',
  '걷기와 뛰기 사이엔 큰 차이가 없다.',
  '뛰다 걸어도 다시 뛰면 그게 러너.',
  '한 번 더 만이 평생을 만든다.',
  '숨 차면 잠시 걷고, 다시 시작하자.',
  '러닝은 숫자보다 감각이다.',
  '오늘은 가벼운 마음으로, 내일은 더 가볍게.',
  '뛰는 사람은 핑계 대신 신발을 신는다.',
  '러닝은 가장 친절한 자기 학대다.',
  '땀 흘린 후의 맥주는 인생 상위 1%.',
  '뛰고 나면 식사가 두 배로 맛있다.',
  '러닝은 식욕도 잠도 정직하게 만든다.',
  '컨디션 점검은 첫 1km에서 끝난다.',
  '뛸수록 날씨에 덜 예민해진다.',
  '러닝은 우산이 필요 없다.',
  '바람과 친구가 되는 가장 빠른 방법.',
  '러닝은 친구 없이도 외롭지 않다.',
  '같이 뛰는 사람은 평생 친구가 된다.',
  '러닝 크루는 어른의 동아리다.',
  '뛸 땐 누구나 평등하다.',
  '거리에 나가면 모두가 러너다.',
  '러닝은 도시를 다시 보게 한다.',
  '내가 사는 동네에 이렇게 길이 많았구나.',
  '러닝은 지도 앱보다 정직하다.',
  '뛰는 시간만큼은 보스도 직원도 없다.',
  '러닝은 가장 평화로운 폭주다.',
  '심장이 두근대는 게 사랑만은 아니다.',
  '러닝 후의 정적은 명상보다 깊다.',
  '뛴 후의 물 한 잔은 술보다 달다.',
  '한 걸음마다 한 가지씩 비우자.',
  '뛴 만큼 비워지고, 그만큼 채워진다.',
  '러닝은 오래된 친구처럼 늘 그 자리에.',
  '오늘 안 나가면 내일도 망설인다.',
  '망설일 시간에 신발을 신자.',
  '러닝은 결심보다 습관이다.',
  '습관이 의지를 이긴다.',
  '뛰는 시간을 캘린더에 못 박아라.',
  '약속처럼 러닝을 잡아라.',
  '러닝은 자기 자신과의 약속이다.',
  '약속을 어기면 가장 슬픈 건 나다.',
  '뛰는 동안엔 시간이 다르게 흐른다.',
  '러닝은 짧고 깊은 쉼표다.',
  '오늘의 페이스는 내일의 자랑이다.',
  '느려도 부끄럽지 않다.',
  '빠르다고 잘난 것도 아니다.',
  '러닝의 진짜 적은 비교다.',
  '내 그림자만 따라가도 충분하다.',
  '뛰는 동안 그림자는 가장 좋은 동료다.',
  '러닝은 가장 단순한 운동이라 가장 강하다.',
  '복잡한 마음은 단순한 발걸음으로 풀린다.',
  '뛴 후엔 언제나 한 단계 가벼워진다.',
  '오늘의 출석은 내일의 컨디션이다.',
  '컨디션은 내가 만든다, 기다리지 말자.',
  '러닝은 결과가 아니라 과정 그 자체.',
  '결승선이 없어도 충분히 즐겁다.',
  '뛰면서 듣는 빗소리는 보너스 트랙.',
  '러닝은 어디서든 시작할 수 있다.',
  '특별한 장비 없이 가능한 자유.',
  '운동화 한 켤레면 충분하다.',
  '러닝은 가장 솔직한 셀프케어.',
  '몸이 알면 마음도 안다.',
  '뛰면 안 풀리던 것도 풀린다.',
  '러닝은 회의 없이 끝나는 회의다.',
  '문제는 발걸음 속도로 작아진다.',
  '뛴 거리는 자존감으로 바뀐다.',
  '오늘의 1km는 미래의 자존감.',
  '러닝은 가장 짧은 휴가다.',
  '20분의 휴가를 내 자신에게.',
  '뛰는 사람은 길을 잃지 않는다.',
  '걸음이 길이 되고, 길이 인생이 된다.',
  '러닝은 인생의 미니어처다.',
  '오르막과 내리막, 그게 인생이다.',
  '평지에선 욕심내고 오르막에선 참자.',
  '내리막에선 자세를 잃지 말자.',
  '러닝은 인내의 작은 모형이다.',
  '오늘의 인내가 내일의 평정심이다.',
  '뛰는 동안엔 미래가 가깝게 느껴진다.',
  '러닝은 미래의 나에게 보내는 선물.',
  '뛰는 만큼 미래의 내가 고마워한다.',
  '오늘의 러닝은 내일 약값이다.',
  '뛰면 병원이 멀어진다.',
  '심장은 뛸수록 젊어진다.',
  '러닝은 가장 저렴한 항노화다.',
  '뛰는 사람은 나이를 잊는다.',
  '20대도 70대도 러너 앞엔 평등하다.',
  '러닝은 평생 친구로 삼기 좋다.',
  '한번 빠지면 헤어나오기 힘들다.',
  '러닝의 중독은 좋은 중독이다.',
  '뛰는 사람의 표정은 다르다.',
  '러닝은 표정을 바꾸는 마법.',
  '뛴 후의 거울은 친구가 된다.',
  '운동복이 잘 어울리는 사람이 멋지다.',
  '뛰는 사람은 핑계가 짧다.',
  '러닝은 변명을 깎아내는 일이다.',
  '오늘 안 되면 내일, 내일 안 되면 모레라도.',
  '꾸준함은 천재를 이긴다.',
  '러닝의 천재는 매일 나가는 사람.',
  '재능은 출석부 앞에서 무력하다.',
  '오늘의 출석이 내일의 재능이다.',
  '러닝은 누구도 대신 해줄 수 없다.',
  '내 다리는 내가 움직인다.',
  '뛰는 동안엔 누구도 날 대신할 수 없다.',
  '러닝은 가장 정직한 1인극이다.',
  '관객은 그림자뿐, 그래서 자유롭다.',
  '뛰면서 노래 흥얼거리면 보너스.',
  '러닝은 가장 빠른 명상.',
  '발걸음이 만트라가 된다.',
  '호흡 박자에 마음이 평온해진다.',
  '러닝은 머리를 비우는 가장 빠른 길.',
  '비워야 채워진다, 발걸음으로 비우자.',
  '뛰면 뇌가 정리된다.',
  '러닝은 책상 앞보다 명료한 사고를 준다.',
  '아이디어는 책상 아닌 길에서 온다.',
  '뛰다 보면 답이 떠오른다.',
  '러닝은 사고의 윤활유다.',
  '몸이 풀리면 생각도 풀린다.',
  '뛰는 동안 굳었던 마음도 부드러워진다.',
  '러닝은 자신감을 적립한다.',
  '오늘의 출석이 내일 한 마디 자신감.',
  '뛴 횟수가 곧 자신감이다.',
  '러닝은 결과 아닌 누적이다.',
  '누적된 발걸음이 곧 나다.',
  '오늘 뛰지 않을 핑계는 100개, 뛸 이유는 단 하나면 충분.',
  '뛰는 이유는 단순하다, 기분이 좋아서.',
  '러닝은 가장 효율적인 행복 루틴.',
  '엔돌핀은 광고에 나오는 만큼 진짜다.',
  '뛰면 진짜로 기분이 좋아진다.',
  '러닝은 약 없는 항우울제다.',
  '심호흡 + 발걸음 = 마음 청소.',
  '뛰면 작은 짜증이 사라진다.',
  '러닝은 짜증의 가장 빠른 출구.',
  '땀과 함께 짜증도 흘러나간다.',
  '뛰는 동안엔 무게가 줄어든다.',
  '러닝은 마음의 다이어트.',
  '몸무게보다 마음 무게가 먼저 줄어든다.',
  '뛰면 거울보다 마음이 가벼워진다.',
  '러닝은 가장 친절한 자기 점검.',
  '오늘 컨디션은 1km에서 알 수 있다.',
  '컨디션 안 좋으면 짧게, 그래도 나가자.',
  '0보다 1이 천 배 낫다.',
  '러닝은 0과 1의 차이를 매일 만든다.',
  '뛰지 않은 0보다 뛴 1이 항상 이긴다.',
  '러닝은 매일 작은 승리를 적립한다.',
  '작은 승리들이 모여 큰 인생이 된다.',
  '뛰는 동안엔 패배할 일이 없다.',
  '나간 순간 이미 이긴 거다.',
  '러닝의 적은 침대다.',
  '침대를 이기면 모든 걸 이긴다.',
  '아침 알람을 이기면 오늘 이긴다.',
  '5분 일찍 일어나면 모든 게 가능하다.',
  '러닝은 알람과의 싸움이다.',
  '뛰는 사람은 시간을 만든다.',
  '바쁘다는 핑계 앞에 러닝은 단단하다.',
  '러닝은 시간 부자의 운동이 아니다.',
  '20분만 빼봐, 일주일이 달라진다.',
  '뛰는 시간은 빼는 게 아니라 만드는 것.',
  '러닝은 자기 시간의 정의를 바꾼다.',
  '뛰면 하루가 길어진다.',
  '러닝 후 시간은 더 또렷하다.',
  '뛴 날의 오후는 길게 느껴진다.',
  '러닝은 시간을 늘리는 마법이다.',
  '뛰는 사람의 시간은 깊어진다.',
  '러닝은 단순함의 끝판왕이다.',
  '복잡할 때일수록 단순하게 뛰자.',
  '복잡한 인생, 단순한 발걸음.',
  '발걸음만큼 정직한 답은 없다.',
  '러닝은 답을 주진 않지만 질문을 정리해준다.',
  '뛰면서 정리되지 않는 고민은 없다.',
  '러닝은 가장 따뜻한 외출.',
  '세상에서 가장 가까운 모험이다.',
  '러닝은 모험을 일상으로 끌어온다.',
  '뛰는 동안엔 누구나 모험가다.',
  '동네 한 바퀴도 작은 탐험.',
  '러닝은 익숙한 길도 새롭게 만든다.',
  '같은 길이 매일 다르게 보인다.',
  '뛰는 사람은 풍경의 작가다.',
  '러닝은 풍경을 다시 쓰는 일이다.',
  '발걸음이 곧 문장이다.',
  '내 발걸음이 오늘의 한 줄.',
  '러닝은 매일 쓰는 일기다.',
  '말 없는 일기, 가장 솔직한 일기.',
  '뛴 거리만큼 마음의 페이지가 늘어난다.',
  '러닝은 마음의 페이지를 채우는 일.',
  '오늘 한 페이지, 내일 한 페이지.',
  '러닝은 페이지가 무한한 책이다.',
  '한 권을 다 못 써도 괜찮다.',
  '뛰는 한 책은 끝나지 않는다.',
  '러닝은 영원히 진행 중인 프로젝트.',
  '결승선 없는 마라톤, 그게 진짜 러닝.',
  '인생의 결승선은 멀지만 발걸음은 가깝다.',
  '발걸음에 집중하면 결승선은 따라온다.',
  '러닝은 작은 약속의 누적이다.',
  '오늘 한 약속이 내일 작은 자존감.',
  '러닝은 자존감의 운동이다.',
  '뛰면 뛸수록 나를 좋아하게 된다.',
  '러닝은 자기애의 가장 건강한 표현.',
  '뛰는 동안엔 나를 가장 사랑할 수 있다.',
  '땀 흘리는 모습이 나다워서 좋다.',
  '러닝은 가장 솔직한 셀카.',
  '뛴 후의 표정은 거짓이 없다.',
  '러닝은 표정을 정리해준다.',
  '뛰면 미간의 주름이 펴진다.',
  '러닝은 가장 자연스러운 보톡스.',
  '뛰는 사람은 어디서든 빛난다.',
  '러닝은 사람을 빛나게 한다.',
  '오늘도 한 걸음, 그게 정답.',
  '내일도 한 걸음, 그러면 충분.',
  '러닝은 매일의 정답이다.',
  '정답이 어렵다면 일단 뛰어라.',
  '러닝은 모호함의 적이다.',
  '발걸음은 명확함의 가장 작은 단위.',
  '명확함을 원한다면 일단 나가자.',
  '러닝은 답이 없는 날의 답이다.',
  '뛰는 동안엔 답이 필요 없다.',
  '러닝은 답을 미루는 가장 건강한 방법.',
  '내일의 답은 오늘의 발걸음에 있다.',
  '러닝은 미래를 예약하는 일.',
  '오늘 뛴 km는 미래의 보험.',
  '뛰는 만큼 미래가 안전해진다.',
  '러닝은 가장 저렴한 보험이다.',
  '몸이 보험이고, 다리가 보험금이다.',
  '뛰는 사람은 노후가 다르다.',
  '러닝은 평생을 위한 적금.',
  '오늘 1km, 미래 100km의 시드.',
  '뛰면 시드머니가 쌓인다.',
  '러닝은 건강의 시드머니다.',
  '뛰는 만큼 자유롭다.',
  '발이 자유로우면 마음도 자유롭다.',
  '러닝은 자유의 가장 단순한 형태.',
  '뛰는 동안엔 누구의 눈치도 안 본다.',
  '러닝은 눈치 없는 시간이다.',
  '오롯이 나만을 위한 시간.',
  '러닝은 이기심의 가장 건강한 발현.',
  '내 시간을 내 자신에게 쓰는 일.',
  '뛰면 자기 시간이 비로소 생긴다.',
  '러닝은 잃었던 시간을 되찾아준다.',
  '오늘도 신발끈을 묶어줘서 고마워.',
  '내일도 신발끈을 묶을 너에게.',
  '러닝은 결국 나에게 보내는 사랑이다.',
];

const koSet = new Set();
const koArr = [];
for (const t of koHand) uniqPush(koArr, koSet, t);

// extend with templated variations to reach 365
const koTemplates = [
  (n) => `${n}번째 신발끈, 오늘도 묶는다.`,
  (n) => `오늘 ${n}km 의 의미, 나만 안다.`,
  (n) => `누적 ${n}일, 멈출 이유가 줄어든다.`,
  (n) => `${n}분 짧은 러닝도 러닝이다.`,
  (n) => `${n}걸음의 무게, 가볍지만 정직하다.`,
  (n) => `${n}일째, 어제의 내가 오늘의 코치다.`,
  (n) => `오늘의 ${n}km, 내일의 한 페이지.`,
  (n) => `${n}분만 뛰자, 그게 시작이다.`,
  (n) => `${n}km 후 마음이 달라진다.`,
  (n) => `누적 ${n}회, 출석부가 늘어간다.`,
];
let i = 1;
while (koArr.length < 365) {
  const tmpl = koTemplates[i % koTemplates.length];
  const num = i + 1;
  const t = tmpl(num);
  if (!uniqPush(koArr, koSet, t)) {
    // fallback — append day index suffix to a random hand line
    const base = koHand[i % koHand.length];
    uniqPush(koArr, koSet, `Day ${num} — ${base}`);
  }
  i++;
  if (i > 5000) break;
}
koArr.length = 365;

// ---------------- EN running (365) ----------------
// Real attributable quotes (carefully chosen well-known ones); rest with NULL author.
const enQuoted = [
  ["To give anything less than your best is to sacrifice the gift.", "Steve Prefontaine"],
  ["A lot of people run a race to see who is fastest. I run to see who has the most guts.", "Steve Prefontaine"],
  ["I run to see who has the most guts.", "Steve Prefontaine"],
  ["Somebody may beat me, but they are going to have to bleed to do it.", "Steve Prefontaine"],
  ["The best pace is a suicide pace, and today looks like a good day to die.", "Steve Prefontaine"],
  ["An athlete cannot run with money in his pockets. He must run with hope in his heart.", "Emil Zatopek"],
  ["If you want to run, run a mile. If you want to experience another life, run a marathon.", "Emil Zatopek"],
  ["When a runner is tired, he runs with his heart.", "Emil Zatopek"],
  ["Great is the victory, but the friendship of all is greater.", "Emil Zatopek"],
  ["Pain is inevitable. Suffering is optional.", "Haruki Murakami"],
  ["The most important thing in the Olympic Games is not to win but to take part.", "Pierre de Coubertin"],
  ["If you have a body, you are an athlete.", "Bill Bowerman"],
  ["There is no such thing as bad weather, only soft people.", "Bill Bowerman"],
  ["Run when you can, walk if you have to, crawl if you must; just never give up.", "Dean Karnazes"],
  ["Somewhere along the line we seem to have confused comfort with happiness.", "Dean Karnazes"],
  ["The miracle isn't that I finished. The miracle is that I had the courage to start.", "John Bingham"],
  ["The body achieves what the mind believes.", "Jim Evans"],
  ["The will to win means nothing without the will to prepare.", "Juma Ikangaa"],
  ["Ask yourself: 'Can I give more?'. The answer is usually: 'Yes'.", "Paul Tergat"],
  ["Running is the greatest metaphor for life, because you get out of it what you put into it.", "Oprah Winfrey"],
  ["I always loved running... it was something you could do by yourself, and under your own power.", "Jesse Owens"],
  ["Long distance running is 90 percent mental and the other half is physical.", "Rich Davis"],
  ["The reason we race isn't so much to beat each other... but to be with each other.", "Christopher McDougall"],
  ["You don't stop running because you get old, you get old because you stop running.", "Christopher McDougall"],
  ["Every morning in Africa, a gazelle wakes up. It knows it must run faster than the fastest lion.", "Abe Gubegna"],
  ["Stadiums are for spectators. We runners have nature and that is much better.", "Juha Vaatainen"],
  ["Running is the classical road to self-consciousness.", "Roger Bannister"],
  ["The man who can drive himself further once the effort gets painful is the man who will win.", "Roger Bannister"],
  ["I don't run to add days to my life, I run to add life to my days.", "Ronald Rook"],
  ["The marathon is a charismatic event. It has everything.", "Bill Rodgers"],
  ["Running is real and relatively simple, but it ain't easy.", "Mark Will-Weber"],
  ["The thoughts that occur to me while I'm running are like clouds in the sky.", "Haruki Murakami"],
  ["I run; therefore I am.", "Bart Yasso"],
  ["Never limit where running can take you.", "Bart Yasso"],
  ["Don't dream of winning, train for it.", "Mo Farah"],
  ["The five S's of sports training are: stamina, speed, strength, skill, and spirit.", "Ken Doherty"],
  ["I run because long after my footprints fade away, maybe I will have inspired a few to reject the easy road.", "Anonymous"],
];

const enHand = [
  "Run the mile you are in.",
  "Discomfort is the price of admission to a meaningful life.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "Slow miles still count.",
  "Show up. Lace up. Move.",
  "There is no finish line for an everyday runner.",
  "One run at a time, one day at a time.",
  "If it doesn't challenge you, it doesn't change you.",
  "Train hard, finish strong.",
  "Easy days make hard days possible.",
  "Listen to your body, but don't always agree with it.",
  "The first mile is a liar.",
  "The second mile is honest.",
  "Mile three is where you find yourself.",
  "Sweat is just fat crying — and joy laughing.",
  "You don't have to be fast. You just have to start.",
  "The runner does not stand still.",
  "Make peace with the pace you have today.",
  "Pace is a feeling, not a number.",
  "Trust the long run.",
  "Recovery is part of training.",
  "Sleep is the cheapest performance enhancer.",
  "Hydration is half the workout.",
  "Form follows fatigue — be kind to your form.",
  "Cadence cures a lot of problems.",
  "Run for the love of it, not for the watch.",
  "The watch lies sometimes — your legs don't.",
  "Compete only with the runner you were yesterday.",
  "There are no shortcuts to anywhere worth going.",
  "Consistency beats intensity.",
  "Showing up is the workout.",
  "Even a bad run is better than no run.",
  "Some days you fly, some days you drag.",
  "Running clears the cache.",
  "Run before you think too much.",
  "Lace them up before doubt sets in.",
  "Hills are speedwork in disguise.",
  "Every hill ends.",
  "Downhills are gifts; don't waste them.",
  "Wind is just resistance training.",
  "Rain runs make the best stories.",
  "Running in winter builds character — and patience.",
  "Run by feel, not by fear.",
  "Breathe in courage, breathe out doubt.",
  "Your only opponent is gravity and ego.",
  "Long runs are a conversation with yourself.",
  "Tempo runs teach you to suffer politely.",
  "Intervals are honesty in physical form.",
  "Strides are joy at full volume.",
  "A runner's calendar is a quiet promise.",
  "The road never owes you a personal best.",
  "Trails forgive the watch.",
  "Nature is a better coach than the algorithm.",
  "Your body is the only gear you truly need.",
  "Don't compare your start to someone else's mile 20.",
  "Walk breaks are not failure.",
  "DNF is data, not defeat.",
  "Every run rewrites the story.",
  "If you are running, you are a runner. Period.",
  "There is no such thing as 'just a jog'.",
  "A 5K still counts. A mile still counts.",
  "The best mile is the one you didn't skip.",
  "The runner's high is real and waiting.",
  "Endorphins don't argue.",
  "Calm is on the other side of a hard run.",
  "Anger leaves with the sweat.",
  "Anxiety walks slower than you do.",
  "Run quiet, think loud — or vice versa.",
  "Ground beneath your feet, sky above. That is enough.",
  "A runner notices the wind, the light, the small dog.",
  "Notice the small things at mile pace.",
  "The streetlight at 6am has its own loyalty.",
  "Sunrise belongs to the early movers.",
  "Sunset runs taste like resolution.",
  "Saturday long runs are a love language.",
  "Tuesday speedwork is a quiet brag.",
  "Sunday recovery is sacred.",
  "Monday miles set the tone.",
  "Friday is for shaking out the week.",
  "Streaks are built one Wednesday at a time.",
  "Habits beat motivation, every time.",
  "Discipline is freedom in disguise.",
  "The schedule protects you from yourself.",
  "Run plans are kind, not strict.",
  "A coach's whisper beats a stranger's shout.",
  "You don't need permission to start.",
  "The gun goes off when you decide.",
  "Beginnings are the hardest miles.",
  "Endings are simpler than they look.",
  "Mile by mile, anything is possible.",
  "Step by step, the marathon shrinks.",
  "Don't outrun your joy.",
  "Speed without joy is a leak.",
  "The runner who smiles finishes lighter.",
  "Smile through mile 22 — it confuses the pain.",
  "Pain is information, not a verdict.",
  "Soreness is a receipt.",
  "Blisters are a coach with bad bedside manner.",
  "Tape it, rest it, run it again.",
  "Foam rolling is forgiveness for tomorrow.",
  "Stretch like you mean it, breathe like you have time.",
  "Mobility is the cheapest insurance.",
  "Strength training is the runner's secret.",
  "Glutes wake up; the run gets easier.",
  "A strong core is a kind teammate.",
  "Posture lifts the lungs.",
  "Eyes up. Shoulders down. Hips forward.",
  "Quick feet beat heavy feet.",
  "Land light. Push back, not down.",
  "Forefoot, midfoot, heel — all are valid.",
  "Cadence around 170-180 is a gift to your knees.",
  "Stride length follows fitness, not the other way.",
  "Keep arms relaxed; the legs will thank you.",
  "Don't fight the road — meet it.",
  "Rhythm is a runner's best friend.",
  "Music or silence — both are tools.",
  "Sometimes the playlist is the workout.",
  "Sometimes the silence is the workout.",
  "Negative splits are quietly satisfying.",
  "Even pacing is a practiced skill.",
  "Patience pays in the second half.",
  "Don't bank time; bank effort.",
  "Goal pace is a request, not a guarantee.",
  "Race day is a celebration, not a test.",
  "The starting line is already a victory.",
  "The finish is just where the watch stops.",
  "Medals are heavy because miles are heavy.",
  "Bibs become souvenirs of who you became.",
  "Spectators see effort; runners feel it.",
  "Volunteers are quiet heroes of the sport.",
  "Aid stations are oases of kindness.",
  "Cup of water, smile of stranger — magic.",
  "The crowd at mile 20 is medicine.",
  "Family at the finish is the real podium.",
  "Run for someone, run for yourself, run for the day.",
  "Charity miles weigh less.",
  "Group runs make hard miles disappear.",
  "Solo runs are conversations with the version coming.",
  "A training partner is a future memory.",
  "A coach turns guesswork into growth.",
  "Beginners deserve the front row.",
  "Veterans deserve a quiet nod.",
  "Every level of runner belongs.",
  "Pace doesn't define purpose.",
  "Time on feet is the truest training.",
  "Volume builds, intensity polishes.",
  "Easy runs are not optional.",
  "Run easy enough to talk in full sentences.",
  "If you can sing, you might be loafing.",
  "If you can't speak, you might be racing.",
  "Heart rate tells the truth your ego won't.",
  "Zone 2 is where champions are built.",
  "Stay aerobic, stay long-term.",
  "VO2max is bought with intervals.",
  "Lactate threshold is the runway to endurance.",
  "Speed comes after the foundation, not before.",
  "Build the engine, then drive it hard.",
  "Long runs build your patience for life.",
  "Marathons humble the cocky.",
  "Marathons reward the consistent.",
  "Marathons love the prepared.",
  "The marathon doesn't care what you wore yesterday.",
  "26.2 doesn't negotiate.",
  "The wall is real; the way through is mental.",
  "Mile 20 is where the marathon begins.",
  "Glycogen is honest about your fueling.",
  "Practice your race fuel before race day.",
  "Nothing new on race day.",
  "Trust your training, then trust it again.",
  "Taper is faith disguised as boredom.",
  "Race week nerves are part of the gift.",
  "Sleep more than you think the week before.",
  "Eat a little extra; you earned it.",
  "Hydrate days before, not minutes before.",
  "Pin your bib, calm your breath.",
  "Smile at the start; suffer in style.",
  "Run within yourself for the first half.",
  "Pour yourself into the second half.",
  "Empty the tank, but cleanly.",
  "There is always a kick if you saved one.",
  "Cross the line for the version who started.",
  "Eat. Sleep. Run. Repeat.",
  "Coffee, road, sky — a complete day.",
  "Running is the cheapest therapist in town.",
  "Running won't fix everything, but it makes everything fixable.",
  "Bad day? Try a 3-miler.",
  "Better day? Try a 5-miler.",
  "Best day? Tell another runner.",
  "Streaks bend; they don't have to break.",
  "Take the rest; protect the streak in your head.",
  "Mileage logs are quiet love letters.",
  "Strava is optional. Showing up is not.",
  "Your watch is a tool, not a judge.",
  "Take a watchless run sometimes.",
  "Your body keeps a better log than the cloud.",
  "Trail miles equal road miles in heart.",
  "Treadmill miles count in winter and pride.",
  "Indoor running is still running.",
  "Travel running is sightseeing with intent.",
  "New cities are best mapped on foot.",
  "Hotel runs make memories that meetings forget.",
  "Run early in summer, run late in winter.",
  "Layer up, layer down, but get out the door.",
  "The first 5 minutes outside are the hardest.",
  "Once you're out, you're 90% done deciding.",
  "Start slow, finish strong, breathe always.",
  "Make peace with the wind; it teaches strength.",
  "Make friends with the rain; it cools you.",
  "Make space for the sun; it pays the bills.",
  "Hot days teach humility.",
  "Cold days teach patience.",
  "Wet days teach grit.",
  "Calm days are gifts; don't waste them on phone time.",
  "A run with a sunset is two runs.",
  "A run before sunrise is borrowed time.",
  "A run on a holiday is a reset button.",
  "A run on your birthday is a quiet candle.",
  "A run after a tough day is a clean slate.",
  "A run before a hard talk is a long exhale.",
  "Run when you're sad; you'll be less sad.",
  "Run when you're happy; you'll remember the day.",
  "Run when you're stuck; legs unstick brains.",
  "Movement is medicine in motion.",
  "Stillness has its place; running comes after.",
  "Don't run angry; run honest.",
  "Don't run injured; run later, run smarter.",
  "Hot showers after long runs heal more than muscles.",
  "Compression socks are a love letter to circulation.",
  "Ice baths are a love letter your body curses then thanks.",
  "Massage is maintenance, not luxury.",
  "Sleep is the secret split.",
  "Eight hours feels like fresh legs.",
  "Naps after long runs are non-negotiable.",
  "Eat the carbs, you earned them.",
  "Eat the protein, you'll need it.",
  "Eat the fruit, your gut likes you back.",
  "Coffee is the universal pre-run.",
  "Banana is the universal mid-run.",
  "Chocolate milk is the universal recovery.",
  "Race-day breakfast is a personal religion.",
  "Salt tablets save the unprepared.",
  "Gels work; just practice.",
  "Real food works; just plan it.",
  "Don't outrun your stomach.",
  "Don't outrun your mind.",
  "The legs follow when the head leads.",
  "The head follows when the legs commit.",
  "Find your why before the alarm rings.",
  "The alarm is the first competitor.",
  "Beat the alarm, win the day.",
  "Beat the bed, win the week.",
  "The bed is undefeated unless you decide otherwise.",
  "Keep the shoes by the door.",
  "Pre-pack the kit the night before.",
  "Make starting frictionless.",
  "Friction is the enemy of habit.",
  "Reduce decisions, raise mileage.",
  "If it's planned, it tends to happen.",
  "Calendar your runs like meetings.",
  "Defend your run time politely but firmly.",
  "Saying no to one thing is saying yes to your run.",
  "Run with intention, even on easy days.",
  "Even shakeouts deserve a posture.",
  "Your warmup is the run before the run.",
  "Skip the warmup, pay later.",
  "Cooldowns are the runner's epilogue.",
  "Always close with two slow minutes.",
  "Stretch a little, stretch consistently.",
  "Mobility before strength, strength before speed.",
  "Strong feet, happy knees, tall hips.",
  "The feet are the silent foundation.",
  "Toe yoga is a real thing — try it.",
  "Single-leg balance is gold for runners.",
  "Plank often, plank short, plank well.",
  "Glute bridges are the runner's morning prayer.",
  "Lunges teach respect for stairs.",
  "Squats teach patience to the impatient.",
  "Cross-training is a cheat code.",
  "Cycling is a runner's quiet ally.",
  "Swimming is recovery in motion.",
  "Yoga is the long-term insurance plan.",
  "Walk on rest days. Don't be still.",
  "Hike between long runs. Adventure heals.",
  "Travel + running = best souvenirs.",
  "A morning run in a new city is a gift.",
  "Pack shoes first, fancy clothes second.",
  "Always know where the laundry is.",
  "Always carry a small water bottle.",
  "Trust the route, but check the map.",
  "Run safer in groups when in doubt.",
  "Wear the reflective gear; the road remembers.",
  "Stay visible; stay vertical.",
  "Headlamps are tiny suns of safety.",
  "Don't argue with cars. You will lose.",
  "Crosswalks are not a request, they are a relief.",
  "Always thank the driver who waves you across.",
  "Wave at other runners. We are a quiet club.",
  "A nod is enough. We see each other.",
  "Beginners deserve grace.",
  "Veterans owe grace.",
  "Speedsters owe humility.",
  "Slowest runner sets the soul of the group.",
  "No-drop runs are no-judgment runs.",
  "Walk-jog plans are perfectly valid.",
  "Couch-to-5K is a rite of passage.",
  "5K is a serious distance done seriously.",
  "10K is a beautiful sweet spot.",
  "Half marathons are honest distances.",
  "26.2 is a journey, not a workout.",
  "Ultras change you in ways you didn't ask for.",
  "Trail ultras teach you about night and patience.",
  "Time goals are tools, not identities.",
  "PRs come; PRs go; the runner remains.",
  "Be loyal to the process; results are guests.",
  "Plateaus are quiet teachers.",
  "Frustration means you care.",
  "Boredom means you need a new route.",
  "Try a new path once a week.",
  "Memorize three loops, switch them often.",
  "Run a place you've never been each month.",
  "Curiosity is fuel.",
  "Wonder is faster than dread.",
  "Notice where the trees lean.",
  "Notice which dogs greet you weekly.",
  "Notice the cafe smells at mile two.",
  "Notice the silence between footsteps.",
  "Notice your own breathing every kilometer.",
  "Make peace with the breath you have.",
  "Breath is the only watch that's always honest.",
  "If breath stays calm, the legs will stay.",
  "If breath frays, slow down — don't quit.",
  "Walk if you must. Don't quit on the run.",
  "Runs end. Habits don't have to.",
  "Tomorrow's run begins with tonight's sleep.",
  "Set the next run before this one ends.",
  "Plan the week on Sunday night.",
  "Review the week on Sunday night.",
  "Celebrate one win every week.",
  "Forgive one missed run every week.",
  "Self-compassion is the long-term performance enhancer.",
  "Be your own kind coach.",
  "Speak to yourself like a teammate.",
  "Run today for the runner you want to be at 80.",
  "Future-you is sending thank you notes.",
  "Past-you would be amazed by where you are.",
  "Present-you is the only one who shows up.",
  "Show up small. Show up often.",
  "Tiny consistent moves outwork heroic bursts.",
  "There is no finish line, only the next run.",
];

const enSet = new Set();
const enArr = []; // each item: {text, author}
for (const [t, a] of enQuoted) {
  const k = t.trim();
  if (k.length < 5 || k.length > 80) continue;
  if (enSet.has(k)) continue;
  enSet.add(k); enArr.push({ text: k, author: a });
}
for (const t of enHand) {
  const k = t.trim();
  if (k.length < 5 || k.length > 80) continue;
  if (enSet.has(k)) continue;
  enSet.add(k); enArr.push({ text: k, author: null });
}

const enTemplates = [
  (n) => `Day ${n}: lace up, head out.`,
  (n) => `Mile ${n}: keep it honest.`,
  (n) => `Week ${n}: small, steady, repeat.`,
  (n) => `Run ${n}: future-you says thanks.`,
  (n) => `Streak day ${n}: protect tomorrow's start.`,
  (n) => `${n} reasons can wait; one run cannot.`,
  (n) => `${n} minutes is enough to change a day.`,
  (n) => `${n} steps in, the noise gets quieter.`,
  (n) => `Workout ${n}: easy, smart, kind.`,
  (n) => `Session ${n}: form first, finish strong.`,
];
let j = 1;
while (enArr.length < 365) {
  const tmpl = enTemplates[j % enTemplates.length];
  const t = tmpl(j + 1);
  const k = t.trim();
  if (k.length >= 5 && k.length <= 80 && !enSet.has(k)) {
    enSet.add(k); enArr.push({ text: k, author: null });
  } else {
    const fb = `Note ${j + 1}: easy run, big return.`;
    if (!enSet.has(fb)) { enSet.add(fb); enArr.push({ text: fb, author: null }); }
  }
  j++;
  if (j > 5000) break;
}
enArr.length = 365;

// ---------------- KO self-care (365) ----------------
const selfHand = [
  '잘 자는 게 가장 큰 자기관리다.',
  '오늘의 휴식이 내일의 컨디션이다.',
  '루틴은 의지보다 강하다.',
  '습관은 작은 결정의 누적이다.',
  '자기관리는 사랑의 가장 조용한 형태.',
  '나를 잘 다루는 사람이 결국 잘 산다.',
  '몸이 좋아지면 마음도 따라온다.',
  '마음이 좋아지면 몸도 따라온다.',
  '잘 먹는 게 멋진 일이다.',
  '한 끼를 정성껏 먹으면 하루가 다르다.',
  '커피보다 물 한 잔이 먼저다.',
  '하루 8잔의 물, 가장 저렴한 약.',
  '아침 햇빛 5분이 멜라토닌을 깨운다.',
  '아침에 밖을 한 번 내다보자.',
  '밤에는 화면을 멀리하자.',
  '잠들기 30분 전엔 숨을 천천히 쉬자.',
  '하루를 닫는 의식 하나만 만들자.',
  '내일을 준비하는 가장 좋은 방법은 오늘 잘 자는 것.',
  '취침 시간이 곧 컨디션의 90%.',
  '늦게 자는 만큼 오늘이 짧아진다.',
  '일찍 자는 사람은 시간을 두 배로 쓴다.',
  '아침 5분 명상이 회의 1시간을 살린다.',
  '심호흡 다섯 번이 약 한 알보다 강하다.',
  '4-7-8 호흡, 잠의 친한 친구.',
  '기지개 한 번이 하루의 기지개다.',
  '책상에서 5분마다 일어서자.',
  '계단을 오를 기회를 놓치지 말자.',
  '걷기는 가장 저렴한 사고 정리법.',
  '하루 만 보, 마음 만 보.',
  '점심 후 10분 산책이 졸음을 이긴다.',
  '햇빛은 무료 보충제다.',
  '자연광 30분이 하루를 바꾼다.',
  '식후 가벼운 산책은 혈당의 친구.',
  '식사는 정성, 간식은 가벼움.',
  '폭식보다 만족식.',
  '공복 시간을 두는 것이 위장의 휴식.',
  '아침 식사는 종일의 컨트롤타워.',
  '단백질은 잊지 말고 챙기자.',
  '식이섬유는 가장 조용한 동맹.',
  '발효식품은 장의 친구다.',
  '물 한 잔이 음료수 다섯 잔보다 낫다.',
  '술은 회복을 늦춘다는 사실을 잊지 말자.',
  '담배는 시간 도둑이다.',
  '카페인은 도구지 정체성이 아니다.',
  '오후 2시 이후의 카페인은 잠을 훔친다.',
  '낮잠 20분은 충전, 그 이상은 부채.',
  '의자에 오래 앉지 말자.',
  '서서 일하는 시간을 늘리자.',
  '눈을 자주 감아주자.',
  '20-20-20 규칙: 20분마다 20피트 떨어진 곳을 20초 보기.',
  '핸드폰을 침실 밖에 두자.',
  '아침 첫 30분은 알림 없이.',
  '저녁 마지막 30분도 알림 없이.',
  '디지털 디톡스는 사치가 아니라 위생.',
  '가끔은 핸드폰 없이 산책하자.',
  '책 한 페이지가 SNS 한 시간을 이긴다.',
  '글을 쓰면 마음이 정리된다.',
  '하루 세 줄 일기, 가장 작은 치료.',
  '감사 일기는 과학적으로 효과 있다.',
  '오늘 잘한 것 한 가지, 적어두자.',
  '내일 할 일 세 가지면 충분하다.',
  '할 일이 많으면 우선순위가 사라진다.',
  '한 번에 한 가지, 그게 효율이다.',
  '멀티태스킹은 신화에 가깝다.',
  '집중 25분, 휴식 5분, 뽀모도로.',
  '딥워크 한 시간이 멀티태스킹 다섯 시간을 이긴다.',
  '몰입은 결과가 아니라 환경에서 온다.',
  '책상을 정리하면 머리가 맑아진다.',
  '청소는 가장 저렴한 자기치유.',
  '버리는 연습이 가지는 연습보다 어렵다.',
  '미니멀은 게으름이 아니라 선택이다.',
  '필요한 것만 두는 용기.',
  '과거의 옷장은 미래의 짐이다.',
  '책장은 내 머릿속 거울.',
  '공간이 마음을 만든다.',
  '햇빛 드는 자리에 화분을 두자.',
  '식물은 조용한 룸메이트다.',
  '음악은 분위기의 옷이다.',
  '플레이리스트가 곧 기분의 환경.',
  '향은 기억을 가장 빨리 부른다.',
  '좋아하는 향 하나는 자기관리의 신호다.',
  '취미 하나는 정신건강의 보험.',
  '잘 못 해도 즐기면 그게 취미.',
  '결과를 비교하지 말고 과정에 머물자.',
  '비교는 도둑이다, 기쁨을 훔친다.',
  'SNS는 남의 하이라이트, 내 것은 내 일상.',
  '내 일상이 가장 든든한 이야기다.',
  '나 자신과 대화하는 시간을 만들자.',
  '혼자만의 시간이 친구의 시간을 살린다.',
  '관계는 충전 후에 잘 굴러간다.',
  '사람을 너무 자주 만나는 것도 피로다.',
  '거절은 자기관리의 한 형태다.',
  '아니오를 말할 줄 아는 사람이 평화롭다.',
  '경계는 친절의 다른 이름.',
  '내 시간은 내가 지킨다.',
  '내 에너지를 누구에게 줄지 정하자.',
  '도와줄 수 없을 땐 도와주지 말자.',
  '먼저 나를 채우고 나서 남에게 나눠주자.',
  '비행기 산소마스크처럼 내가 먼저.',
  '이타심도 자기 자원에서 나온다.',
  '자존감은 결과가 아니라 일관성에서 온다.',
  '약속을 지키는 사람이 자기를 신뢰한다.',
  '나에게 한 약속이 가장 중요하다.',
  '오늘 한 작은 약속, 내일의 큰 자존감.',
  '루틴은 자기 신뢰의 적금이다.',
  '습관은 의지의 자동화다.',
  '환경을 바꾸면 습관이 따라온다.',
  '신호 → 갈망 → 반응 → 보상.',
  '신호를 만들면 행동이 따라온다.',
  '문 옆에 운동화를 두는 것도 디자인이다.',
  '냉장고 첫 줄에 과일을 두자.',
  '간식 서랍을 식탁 옆에 두지 말자.',
  '자기관리는 의지가 아니라 설계다.',
  '나쁜 습관의 코스트를 시각화하자.',
  '좋은 습관의 보상을 시각화하자.',
  '체크리스트는 자존감의 시각화.',
  '캘린더에 X 표시 하나가 동기부여다.',
  '연속 출석을 끊지 말자.',
  '끊어졌다면, 다음 칸에 X.',
  '완벽보다 지속.',
  '한 번 실패는 한 번일 뿐이다.',
  '두 번 연속 빠지지 말자, 그게 룰.',
  '실수는 데이터다, 도덕이 아니다.',
  '자책 대신 분석.',
  '나를 혼내는 시간에 다시 시작하자.',
  '셀프토크는 가장 자주 듣는 말이다.',
  '내가 나에게 하는 말이 곧 나다.',
  '거울 앞에서 한 번 웃어주자.',
  '아침에 자기 자신에게 인사하자.',
  '자기 칭찬은 부끄러운 일이 아니다.',
  '오늘 한 잘한 일을 큰 소리로 말하자.',
  '실수했어도 괜찮다고 말해주자.',
  '내 안의 비판자는 가끔 음소거하자.',
  '내 안의 응원자를 키우자.',
  '심리 안전은 누구도 대신 못 만든다.',
  '안전한 마음은 안전한 잠을 부른다.',
  '잠 환경부터 점검하자.',
  '침실은 조금 시원하게.',
  '암막 커튼은 수면의 친구.',
  '백색소음은 예민한 잠의 베프.',
  '잠들기 전 따뜻한 샤워.',
  '베개의 높이도 회복의 변수다.',
  '아침 햇빛이 잠을 만든다.',
  '저녁 식사는 일찍, 가볍게.',
  '취침 3시간 전 식사 끝.',
  '취침 1시간 전 화면 끄기.',
  '잠들기 전 책 한 챕터.',
  '주말의 늦잠은 시차를 만든다.',
  '같은 시간에 자고 일어나자.',
  '주말도 평일과 비슷하게.',
  '루틴의 적은 휴일이 아니다, 모호함이다.',
  '명확한 시간이 자유를 만든다.',
  '아침 루틴 5단계만 정해두자.',
  '저녁 루틴 5단계만 정해두자.',
  '아침과 저녁의 의식이 하루를 묶어준다.',
  '점심 후 10분 산책 의식.',
  '식사 전 한 잔의 물.',
  '식사는 천천히, 20번 씹기.',
  '식사 중엔 화면을 멀리.',
  '입에 들어가는 것이 곧 컨디션.',
  '오늘의 컨디션은 어제의 식사.',
  '내일의 컨디션은 오늘의 식사.',
  '한 끼를 정성껏 차리는 것은 자기 존중.',
  '혼밥도 식탁을 차려보자.',
  '예쁜 그릇에 담으면 식사가 달라진다.',
  '간단한 요리 레시피 5개면 충분하다.',
  '계란 하나로도 한 끼.',
  '바나나 하나로도 한 끼.',
  '냉장고 비우기는 자기관리의 일종.',
  '먹을 만큼만 사기.',
  '계획적인 장보기는 시간과 돈의 친구.',
  '주말에 한 번, 식단을 점검하자.',
  '간단한 식단표가 의지보다 강하다.',
  '주간 시리얼 루틴, 평일 큰 차이.',
  '주말 1시간 밀프렙, 평일 1시간 절약.',
  '식사도 결국 디자인.',
  '운동복은 보이는 곳에.',
  '운동기구는 손 닿는 곳에.',
  '책은 자주 보는 자리에.',
  '핸드폰은 안 보이는 곳에.',
  '환경 디자인이 의지를 이긴다.',
  '의지는 약하다, 시스템은 강하다.',
  '시스템이 결과를 만든다.',
  '결과보다 시스템에 집중하자.',
  '오늘의 시스템이 내일의 결과.',
  '결과는 후행지표, 시스템은 선행지표.',
  '눈에 보이는 결과만 쫓지 말자.',
  '안 보이는 누적이 결국 보인다.',
  '복리는 재테크에만 있는 게 아니다.',
  '습관은 인생의 복리다.',
  '오늘 1%, 1년 후 38배.',
  '작은 차이가 쌓이면 큰 차이다.',
  '하루의 1%만 자기 자신에게 쓰자.',
  '하루 14분이면 1%다.',
  '14분 명상, 14분 산책, 14분 책.',
  '시간이 없는 게 아니라 우선순위가 다르다.',
  '바쁘다는 말 대신 안 한다는 말.',
  '안 한다는 말이 정직하다.',
  '내 시간을 정직하게 들여다보자.',
  '시간 가계부 일주일이면 진실이 보인다.',
  '시간을 추적하면 시간이 늘어난다.',
  '돈처럼 시간을 예산하자.',
  '내 시간의 가격을 알자.',
  '시간 절약 1순위는 핸드폰 시간 줄이기.',
  '하루 30분만 줄여도 책 한 권.',
  '한 시간 줄이면 일주일에 영화 두 편.',
  '핸드폰은 도구지 친구가 아니다.',
  '알림은 디폴트 무음.',
  '필요한 알림만 남기자.',
  '메신저 답장 시간을 정해두자.',
  '늘 답장 가능한 사람은 자기 시간이 없다.',
  '답장 늦어도 미안하지 않아도 된다.',
  '메일은 하루 두 번만 열자.',
  '회의는 짧을수록 좋은 회의.',
  '15분 회의면 15분으로 끝나도록.',
  '회의 없는 날을 정해두자.',
  '딥워크 시간을 캘린더에 박아두자.',
  '딥워크 90분이 하루를 만든다.',
  '오전이 가장 비싼 시간이다.',
  '가장 중요한 일을 오전에.',
  '아침엔 창의적인 일을, 오후엔 행정.',
  '에너지의 시간대를 알면 인생이 효율적.',
  '내 컨디션 곡선을 그려보자.',
  '주간 리뷰는 자기관리의 핵심 의식.',
  '월간 리뷰는 방향의 점검.',
  '연간 리뷰는 인생의 점검.',
  '매주 일요일 30분 리뷰.',
  '잘된 것 / 안된 것 / 다음 주 할 것.',
  '리뷰는 자책이 아니라 학습.',
  '실패는 빠른 회복의 재료.',
  '실패의 비용을 줄이는 게 진짜 능력.',
  '회복탄력성은 훈련된다.',
  '실패 후 24시간 안에 다시 시작하자.',
  '두 번째 시도는 첫 번째보다 가볍다.',
  '세 번째 시도쯤엔 익숙해진다.',
  '습관은 21일이 아니라 66일에 가까워진다.',
  '평균 66일이라는 연구가 있다.',
  '두 달은 견디자, 그러면 자동이 된다.',
  '60일을 견디는 게 자기관리의 본질.',
  '결국 매일 하는 사람만 남는다.',
  '꾸준한 사람을 부러워하지 말고 따라하자.',
  '롤모델 한 명, 가까이 두자.',
  '환경의 사람도 자기관리의 일부.',
  '주변 다섯 명의 평균이 곧 나.',
  '같이 자라는 사람을 만나자.',
  '혼자 잘하기보다 같이 잘하기.',
  '커뮤니티는 동기의 보충제.',
  '한 명의 친구가 한 권의 책보다 강할 때.',
  '멘토는 멀리 있지 않다.',
  '책도 멘토가 될 수 있다.',
  '한 달에 한 권만 읽어도 1년 12권.',
  '독서는 가장 저렴한 멘토링.',
  '오디오북은 출퇴근의 친구.',
  '팟캐스트는 산책의 동료.',
  '뉴스 다이어트도 자기관리.',
  '뉴스는 양보다 출처.',
  '뉴스는 매일 보지 않아도 된다.',
  '관심사 큐레이션이 곧 정신 건강.',
  '내가 보는 것이 곧 내가 된다.',
  '눈에 들어오는 것을 디자인하자.',
  '계정 정리도 자기관리.',
  '안 보고 싶은 계정은 과감히 끄자.',
  '팔로우는 영양분 선택과 같다.',
  '시간이 짧으면 정보가 깨끗해야 한다.',
  '정보 다이어트가 결국 마음 다이어트.',
  '잘 모르는 일에 의견을 내지 말자.',
  '판단을 잠시 미루는 연습.',
  '여백이 인생의 질을 만든다.',
  '일정에 30%는 빈 시간으로.',
  '여유 시간이 진짜 시간이다.',
  '바쁘다고 자랑하지 말자.',
  '여유는 무능이 아니라 지혜.',
  '쉴 줄 아는 사람이 오래 간다.',
  '뜨거운 사람보다 지속하는 사람.',
  '에너지는 회복으로 채워진다.',
  '회복 없는 노력은 번아웃이다.',
  '번아웃은 갑자기 오지 않는다.',
  '미세한 신호를 무시하지 말자.',
  '두통, 어깨, 위장이 먼저 신호한다.',
  '몸의 신호를 일찍 듣는 사람이 건강하다.',
  '병원은 늦지 말자.',
  '연 1회 검진은 자기관리의 기본.',
  '치과는 6개월에 한 번.',
  '안과 검진은 매년.',
  '심리상담도 자기관리의 일부.',
  '약 먹는 건 부끄러운 일이 아니다.',
  '도움 요청은 강함의 표현이다.',
  '약함을 인정하는 게 진짜 강함.',
  '울고 싶을 땐 울자.',
  '눈물은 가장 정직한 디톡스.',
  '감정은 데이터지 도덕이 아니다.',
  '슬픔도 정보다.',
  '분노도 신호다.',
  '불안도 메시지다.',
  '감정에 이름을 붙이면 작아진다.',
  '오늘 기분 한 단어로 적어보자.',
  '기분일기 한 줄, 마음의 체온계.',
  '아침 1분 명상.',
  '저녁 1분 감사.',
  '하루 2분의 의식, 1년이 바뀐다.',
  '명상은 마음의 양치질.',
  '안 하면 쌓인다.',
  '잘 모르겠으면 일단 5분 호흡.',
  '5분 호흡이 약 한 알을 이긴다.',
  '걸으며 하는 명상도 명상이다.',
  '설거지하며 하는 명상도 명상이다.',
  '의식적인 모든 행위가 명상이 될 수 있다.',
  '바른 자세가 의식을 만든다.',
  '척추를 세우면 마음이 선다.',
  '어깨를 내리면 호흡이 깊어진다.',
  '턱을 당기면 두통이 줄어든다.',
  '하루 한 번 자세 점검.',
  '의자가 좋아야 인생이 좋다.',
  '책상 높이가 어깨를 결정한다.',
  '모니터를 눈높이에 맞추자.',
  '키보드와 마우스도 도구다.',
  '도구를 잘 쓰면 몸이 편하다.',
  '스마트폰 거북목, 작은 디톡스로 풀자.',
  '하루 5분 거북목 스트레칭.',
  '목과 어깨는 매일 풀어주자.',
  '엉덩이 근육은 자주 깨워주자.',
  '오래 앉으면 뇌도 굳는다.',
  '서서 일하는 시간을 늘리자.',
  '계단 5층은 에스프레소 한 잔의 효과.',
  '대중교통은 걷기의 기회다.',
  '한 정거장 미리 내리는 사람은 다르다.',
  '약속 장소까지 걸어서 가보자.',
  '우산보다 패딩, 변명을 줄이자.',
  '날씨는 핑계가 될 수 없다.',
  '준비물은 의지의 전조다.',
  '가방에 운동복을 항상 두자.',
  '여행 짐에도 운동화를 챙기자.',
  '여행은 루틴을 시험하는 무대.',
  '루틴이 무너져도 다시 시작하면 된다.',
  '여행 후 첫날, 가장 중요한 회복.',
  '바쁠 때일수록 기본이 중요하다.',
  '잠 / 식사 / 움직임, 이 셋만 지키자.',
  '이 셋이 무너지면 나머지도 무너진다.',
  '이 셋만 지키면 어떤 위기도 견딘다.',
  '자기관리의 본질은 단순함이다.',
  '복잡한 시스템은 오래 못 간다.',
  '단순한 규칙 셋이면 충분하다.',
  '단순함은 지속의 어머니.',
  '오래 갈 수 있는 강도가 진짜 강도.',
  '20%의 노력으로 80%의 효과.',
  '핵심에 집중, 나머지는 흘려보내자.',
  '자기관리는 마라톤이다.',
  '단거리 전력질주는 탈진을 부른다.',
  '오래 가는 사람이 결국 도착한다.',
  '오늘도 한 칸 채웠다, 그걸로 충분.',
  '내일도 한 칸 더, 그게 인생.',
  '한 칸 한 칸이 결국 캘린더 한 장.',
  '캘린더 한 장이 결국 한 해.',
  '꾸준함은 한 번에 만들어지지 않는다.',
  '꾸준함은 매일 새로 만들어진다.',
  '오늘의 나는 매일 새로 태어난다.',
  '어제의 나에게 친절하자.',
  '오늘의 나에게 정직하자.',
  '내일의 나에게 약속하자.',
  '세 가지가 자기관리의 골격.',
  '몸 / 마음 / 시간 — 세 축의 균형.',
  '한 축이 무너지면 다른 두 축도 흔들린다.',
  '균형은 정적이 아니라 끊임없는 조정.',
  '오늘의 균형은 오늘만의 답.',
  '내일은 또 다른 답이 필요할 수도.',
  '유연한 사람이 결국 단단하다.',
  '단단한 사람이 결국 부서진다.',
  '대나무처럼 휘되 꺾이지 말자.',
  '바람이 불 때 잠시 굽히는 것도 지혜.',
  '잠시 굽힌 것이 영원히 굽힌 것은 아니다.',
  '자기관리는 자기 자비의 다른 이름.',
  '나에게 친절한 만큼 멀리 간다.',
  '오늘도 나를 돌봐주어 고마워.',
];

const selfSet = new Set();
const selfArr = [];
for (const t of selfHand) uniqPush(selfArr, selfSet, t);

const selfTemplates = [
  (n) => `Day ${n}: 작게, 자주, 부드럽게.`,
  (n) => `${n}일째 루틴, 의지보다 시스템.`,
  (n) => `Week ${n}: 잠 / 식사 / 움직임만 지키자.`,
  (n) => `${n}분만 나에게 쓰자.`,
  (n) => `${n}일 후의 나에게 보내는 발걸음.`,
  (n) => `${n}번째 작은 약속, 자존감의 적금.`,
  (n) => `Note ${n}: 비교 끄고 과정 켜기.`,
  (n) => `Streak ${n}일, 환경이 의지를 도왔다.`,
  (n) => `${n}회차 자기 점검, 데이터로 친절하게.`,
  (n) => `${n}일치 회복, 내일의 컨디션이 됨.`,
];
let k2 = 1;
while (selfArr.length < 365) {
  const tmpl = selfTemplates[k2 % selfTemplates.length];
  const t = tmpl(k2 + 1);
  if (!uniqPush(selfArr, selfSet, t)) {
    const fb = `Note ${k2 + 1}: 오늘도 한 칸 채우기.`;
    uniqPush(selfArr, selfSet, fb);
  }
  k2++;
  if (k2 > 5000) break;
}
selfArr.length = 365;

// ---------------- Build SQL ----------------
function valKo(t) {
  return `('ko', 'running', '${esc(t)}', NULL)`;
}
function valEn(o) {
  const a = o.author ? `'${esc(o.author)}'` : 'NULL';
  return `('en', 'running', '${esc(o.text)}', ${a})`;
}
function valSelf(t) {
  return `('ko_self', 'self_care', '${esc(t)}', NULL)`;
}

function chunked(values, perStmt = 100) {
  const stmts = [];
  for (let i = 0; i < values.length; i += perStmt) {
    const slice = values.slice(i, i + perStmt);
    stmts.push(
      `INSERT INTO public.quotes (lang, category, text, author) VALUES\n  ${slice.join(',\n  ')};`
    );
  }
  return stmts;
}

const sqlParts = [];
sqlParts.push('-- Routinist 1-year quote seed (1095 rows: ko/en/ko_self × 365)');
sqlParts.push('-- Generated by supabase/seeds/build_quotes.js');
sqlParts.push("DELETE FROM public.quotes WHERE category IN ('running', 'self_care');");
sqlParts.push(...chunked(koArr.map(valKo)));
sqlParts.push(...chunked(enArr.map(valEn)));
sqlParts.push(...chunked(selfArr.map(valSelf)));

const sql = sqlParts.join('\n\n') + '\n';
fs.writeFileSync(path.join(__dirname, 'quotes_seed.sql'), sql);
console.log('ko:', koArr.length, 'en:', enArr.length, 'self:', selfArr.length, 'bytes:', sql.length);
